# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

#S3_BUCKET_NAME: "linklabforest"
#AWS_ACCESS_KEY_ID: "AKIAR2U6QFO76IPDSVCK"
#AWS_SECRET_ACCESS_KEY: "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"
#AWS_REGION: "us-east-2"
GMAIL_USERNAME: "lamnguyen04.97@gmail.com"
GMAIL_PASSWORD: "bmnmezvmkkjmfxwh"

#GMAIL_USERNAME: "tvhd@thptbinhhunghoa.edu.vn"
#GMAIL_PASSWORD: "tlrfottgeuwdhrot"

DATABASE_NAME: high_school_development
MYSQL_USER: postgres
MYSQL_PASSWORD: "123456"
MYSQL_ROOT_PASSWORD: "123456"

HELLO: world
development:
  HELLO: developers
production:
  HELLO: users

